name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libgl-dev libxcursor-dev libxrandr-dev
      - name: build sowon
        run: |
          make
        env:
          CC: gcc
  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libgl-dev libxcursor-dev libxrandr-dev
      - name: build sowon
        run: |
          make
        env:
          CC: clang
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: build sowon
        run: |
          make
        env:
          CC: clang
  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: build sowon
        shell: cmd
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          ./build_msvc.bat
# TODO: FreeBSD build is broken
#  build-freebsd:
#    runs-on: macos-latest
#    name: FreeBSD LLVM Clang build
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build on FreeBSD
#        id: build
#        uses: vmactions/freebsd-vm@v0.0.9
#        with:
#          usesh: true
#          prepare: pkg install -y sdl2 pkgconf
#          run: |
#            freebsd-version
#            make
